#!/bin/sh

### BEGIN INIT INFO
# Provides:        sim-gpio
# Required-Start:  $network $remote_fs
# Required-Stop:   $network $remote_fs 
# Default-Start:   2 3 4 5
# Default-Stop: 
# Short-Description: Start simGPIO daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON=/home/pi/simGPIODriver/simGPIODriver
PIDFILE=/var/run/simGPIO.pid

test -x $DAEMON || exit 5



RUNASUSER=pi

case $1 in
	start)
		log_daemon_msg "Starting simGPIODriver" "simGPIO"
		start-stop-daemon --start --background --pidfile $PIDFILE --startas $DAEMON -- 
		status=$?
		log_end_msg $status
  		;;
	stop)
		log_daemon_msg "Stopping simGPIODriver" "simGPIO"
  		start-stop-daemon --stop --pidfile $PIDFILE
		log_end_msg $?
		rm -f $PIDFILE
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc $DAEMON "simGPIO driver"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
